/*
* generated by Xtext
*/
package de.bomzhi.petrinet.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class PetrinetDslOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
