/*
* generated by Xtext
*/
package de.bomzhi.petrinet.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import de.bomzhi.petrinet.services.PetrinetDslGrammarAccess;

public class PetrinetDslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private PetrinetDslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected de.bomzhi.petrinet.parser.antlr.internal.InternalPetrinetDslParser createParser(XtextTokenStream stream) {
		return new de.bomzhi.petrinet.parser.antlr.internal.InternalPetrinetDslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "PetriNet";
	}
	
	public PetrinetDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(PetrinetDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
