/*
 * generated by Xtext
 */
package de.bomzhi.petrinet;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PetrinetDslRuntimeModule extends de.bomzhi.petrinet.AbstractPetrinetDslRuntimeModule {

}
