/*
* generated by Xtext
*/
package de.bomzhi.petrinet.ui.contentassist;

import de.bomzhi.petrinet.ui.contentassist.AbstractPetrinetDslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class PetrinetDslProposalProvider extends AbstractPetrinetDslProposalProvider {

}
