/*
 * generated by Xtext
 */
package de.bomzhi.petrinet.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class PetrinetDslUiModule extends de.bomzhi.petrinet.ui.AbstractPetrinetDslUiModule {
	public PetrinetDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
